[package]
name = "crab_torrent"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
percent-encoding = "2.3.1"
reqwest = { version = "0.12.11", features = ["blocking"] }
sha1 = "0.10.6"
thiserror = "2.0.9"
